name: Daily Prediction Update
permissions:
  contents: write
  pull-requests: write

on:
  schedule:
    - cron: '0 10 * * *'  # Run at 10 UTC
  workflow_dispatch:     # Allow manual trigger

jobs:
  update-forecast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev
        
      - name: Install needed R packages
        run: Rscript -e 'install.packages(c("curl","readr","dplyr","tidyr","stringr","glue","arrow"), repos = "https://cloud.r-project.org")'


          
      - name: Set forecast date and output file
        run: |
          FORECAST_DATE=$(date -d "9 days ago" +%F)
          echo "FORECAST_DATE=$FORECAST_DATE" >> $GITHUB_ENV
          echo "OUTPUT_FILE=data/outputs/forecast_prediction-$FORECAST_DATE.csv" >> $GITHUB_ENV

      - name: Run daily forecast script
        run: Rscript scripts/daily_prediction.R "$FORECAST_DATE"

      - name: Configure Git with your user info
        run: |
          git config --global user.name "jmzobitz"
          git config --global user.email "zobitz@augsburg.edu"

      - name: Set branch name
        run: echo "BRANCH=daily-forecast-update-${{ env.FORECAST_DATE }}" >> $GITHUB_ENV


      - name: Commit forecast update to branch
        run: |
          git checkout -B $BRANCH
          git add "$OUTPUT_FILE" || echo "No file to add"
          git commit -m "Add forecast output for $FORECAST_DATE" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git
          git push origin $BRANCH --force || echo "Push failed or nothing to push"

      - name: Create and merge pull request
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          # Only create PR if it doesn't already exist
          if gh pr view $BRANCH --json number > /dev/null 2>&1; then
            echo "PR already exists for $BRANCH"
          else
            gh pr create \
              --base main \
              --head $BRANCH \
              --title "Auto PR: Forecast update $FORECAST_DATE" \
              --body "Automated forecast update."
          fi

          # Merge and auto-delete branch if PR exists
          if gh pr view $BRANCH --json number > /dev/null 2>&1; then
            gh pr merge --squash --admin --delete-branch || echo "Merge failed"
          else
            echo "No PR to merge"
          fi