name: Daily Forecast Update

on:
  schedule:
    - cron: '0 6 * * *'  # Run at 6 AM UTC every day
  workflow_dispatch:     # Allow manual trigger

jobs:
  update-forecast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies for terra
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgdal-dev \
            libproj-dev \
            libgeos-dev \
            libudunits2-dev \
            libcurl4-openssl-dev \
            libxml2-dev

      - name: Install renv
        run: Rscript -e 'install.packages("renv", repos = "https://cloud.r-project.org")'

      - name: Restore R environment
        run: Rscript -e 'renv::restore()'

      - name: Run daily forecast script
        run: Rscript scripts/daily_forecast.R

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Commit forecast update to branch
        run: |
          BRANCH="daily-update"
          git checkout -B $BRANCH
          git add data/drivers/observed_soil_drivers.csv
          git commit -m "Daily forecast update: $(date -u +'%Y-%m-%d')" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git $BRANCH

      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Daily forecast update: $(date -u +'%Y-%m-%d')"
          branch: daily-update
          title: "Daily forecast update: $(date -u +'%Y-%m-%d')"
          body: "This pull request includes the forecast data for the previous day."
          base: main

      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
