name: Daily Forecast Acquisition

on:
  schedule:
    - cron: '0 6 * * *'  # Runs every day at 6 AM UTC
  workflow_dispatch:      # Allows manual trigger if needed

jobs:
  acquire-forecast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Install system dependencies for terra
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgdal-dev \
            libproj-dev \
            libgeos-dev \
            libudunits2-dev \
            libcurl4-openssl-dev \
            libxml2-dev
          
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.0'

      - name: Install renv
        run: |
          Rscript -e 'install.packages("renv", repos = "https://cloud.r-project.org")'


      - name: Restore R Packages
        run: Rscript -e 'renv::restore()'

      - name: Run forecast update script
        run: |
          Rscript -e '
            source("R/acquire_forecast.R")
            input_date <- as.character(Sys.Date() - 1)
            current_drivers <- readr::read_csv("data/drivers/observed_soil_drivers.csv")
            input_drivers <- acquire_forecast(input_date, forecast_vals = "gec00", forecast_horizon = "f000") |>
              dplyr::mutate(date = input_date) |>
              tidyr::pivot_wider() |>
              dplyr::relocate(date, field_site_id) |>
              dplyr::rename(site = field_site_id)
            out_drivers <- rbind(current_drivers, input_drivers)
            readr::write_csv(out_drivers, file = "data/drivers/observed_soil_drivers.csv")
          '

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/drivers/observed_soil_drivers.csv
          git commit -m "Daily forecast update: $(date -u +"%Y-%m-%d")" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
